name: Approved Deployment to Production Pipeline

on:
  workflow_call:

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
      - name: Deploying to Prod
        run: |
          echo "Deploying to Prod. Can use Environment secrets or secrets passed in RUW call here to authenticate if required"
          exit 0
      
